name: "Terragrunt"

on:
  push:
    branches:
      - main
      - '*'
  pull_request:
    branches:
      - main

env:
  TERRAGRUNT_VERSION: 0.44.5
  TERRAFORM_VERSION: 1.2.6

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run Checkov action #https://www.checkov.io/5.Policy%20Index/terraform.html
        id: checkov
        uses: bridgecrewio/checkov-action@v12.765.0
        continue-on-error: true
        with:
          directory: .
          skip_check: CKV_GCP_2
          quiet: true # optional: display only failed checks

      - name: Lint Code Base
        uses: github/super-linter@v4
        continue-on-error: true
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_SHELL_SHFMT: false 
          VALIDATE_GO: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  terraform_format_check:
    name: Terraform Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0        

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Format Check
        run: terraform fmt -list=true -check=true -recursive

  terragrunt_plan_apply:
    name: Terragrunt Plan and Apply
    runs-on: ubuntu-latest
    needs: [terragrunt_validate] #[lint, terragrunt_validate]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Terragrunt
        run: |
          wget https://github.com/gruntwork-io/terragrunt/releases/download/v${TERRAGRUNT_VERSION}/terragrunt_linux_amd64 -O terragrunt
          sudo chmod u+x terragrunt && sudo mv terragrunt /usr/local/bin/terragrunt
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false

      - name: Terragrunt Init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          for dir in $(find $GITHUB_WORKSPACE/environments -maxdepth 1 -mindepth 1 -type d); do
            echo "Running init in $dir"
            cd $dir
            terragrunt run-all init --terragrunt-non-interactive
          done

      - name: Terragrunt Plan
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          for dir in $(find $GITHUB_WORKSPACE/environments -maxdepth 1 -mindepth 1 -type d); do
            echo "Running plan in $dir"
            cd $dir
            terragrunt run-all plan --terragrunt-non-interactive
          done

      - name: Terragrunt Apply
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: |
          for dir in $(find $GITHUB_WORKSPACE/environments -maxdepth 1 -mindepth 1 -type d); do
            echo "Running apply in $dir"
            cd $dir
            terragrunt run-all apply --terragrunt-non-interactive
          done